name: CI
on: [pull_request, push]
jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 11 ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java_version }}
      - name: Spotless checks
        run: ./gradlew spotlessCheck --stacktrace
      - name: Build the app
        run: ./gradlew build
